### ISSUE TITLE
[Suggestion] Ability to set a custom Time Out?

### ISSUE THREAD

**Issue by wolfpepper** [inferno-collection/Fire-EMS-Pager#12]
Is your feature request related to a problem? Please describe.

The possibility to add a custom Timeout With the page Tone

Describe the solution you would like

Adding the ability to place a custom timeout or leave the field blank and have it fall back onto the Randomizer which i know is easier said then done

Describe alternatives you have considered

N/A

Additional context

N/A

**Comment by cm8263** [comment]
Hello @wolfpepper,

Thanks for your suggestion; could you be a little more specific about what part of the timeout you would like to add to? At present it is already fairly customisable:

```lua
args = {"Fire Control", "\nAttention " .. config.deptName .. " - " .. newDetails .. " - " .. newTones .. "Emergency.\n\nTimeout " .. hours .. minutes.. "."}
```

Where `newDetails` are the details included in the `/page` command, and `newTones` being the tones paged in the `/page` command.

Or if you are using the default details:
```lua
config.defaultDetails = "Report to Station"
...
args = {"Fire Control", "\nAttention " .. config.deptName .. " - " .. config.defaultDetails .. ".\n\nTimeout " .. hours .. minutes.. "."}
```
***
Unless you are talking *specificly* about the timeout part of the message, in which case you can just add to or remove from it as you like 👍 

Thanks,
- Christopher
