### ISSUE TITLE
I can't change your tone

### ISSUE THREAD

**Issue by flo42150** [inferno-collection/Fire-EMS-Pager#17]
(sorry for my english in advance)
I need help because I always have the same tone (vibrate.mp3). But not the others even by choosing for example (fire) or (medical). I even added custom tones but I still have the same (vibrate.mp3) without hearing my custom tones.
Do you have a solution?
thank you so much

**Comment by cm8263** [comment]
Solved through Discord; was a misunderstanding of the way the resource worked.
