### ISSUE TITLE
[Suggestion] Updating the Script for External Use

### ISSUE THREAD

**Issue by Squad3tm** [inferno-collection/Fire-EMS-Pager#18]
**Is your feature request related to a problem? Please describe.**
More of a feature "update" request

**Describe the solution you would like**
I'd like for the script that allows external use to be updated to the latest version, the script I'm supposed to replace is far different than the current version.

**Describe alternatives you have considered**
The other external use, which is not recommended.

**Additional context**
https://github.com/inferno-collection/Fire-EMS-Pager/wiki/Calling-the-pager-from-an-external-resource

^This is the page I'm talking about.

Thank you so much for doing this!

**Comment by cm8263** [comment]
The wiki page has been updated, thank you for bringing this to our attention.
