### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MadLad1Clip** [inferno-collection/Fire-EMS-Pager#21]
Attemping to run the firesiren fails thowing console error 

![image](https://user-images.githubusercontent.com/5630104/99916467-39552d00-2d02-11eb-8b29-b9dbf72568cf.png)

**Comment by cm8263** [comment]
If you are trying to use the export, likely the same issue as [here](https://github.com/inferno-collection/Fire-EMS-Pager/issues/22).
