### ISSUE TITLE
cant export firesiren

### ISSUE THREAD

**Issue by Wick89** [inferno-collection/Fire-EMS-Pager#22]
I'm looking at your Calling the fire siren from an external resource on Wiki

function soundFireSiren(Args) -- but with SoundFireSiren with large S can I chat /firesiren
	if Whitelist.Command.firesiren then
		local ToBeSirened = {}
		-- Loop though all the stations provided in the command
		for _, ProvidedStation in ipairs(Args) do -- my error is now it one

![bug3](https://user-images.githubusercontent.com/44001562/108887163-2b1cf280-760a-11eb-83f9-433ee5601b55.png)
![bug4](https://user-images.githubusercontent.com/44001562/108887184-32440080-760a-11eb-876b-dd316660d842.png)

and yes have made it here in my scripts
stations = {"pb", "fz", "ss"}

exports["inferno-fire-ems-pager"]:SoundFireSiren(Stations)

so you have an error somewhere??

**Comment by cm8263** [comment]
> stations = {"pb", "fz", "ss"}

You're using lowercase here, and uppercase here

> exports["inferno-fire-ems-pager"]:SoundFireSiren(Stations)

That's likely not helping.

**Comment by Wick89** [comment]
oh i see it again a large S

you have some small s need to be large S 

`function soundFireSiren(Args)
	if Whitelist.Command.firesiren then`
and
stations = {"pb", "fz", "ss"}

work ned is it now works with large S
updated your Calling the fire siren from an external resource in Wiki

**Comment by cm8263** [comment]
Glad the issue was solved.
