### ISSUE TITLE
[Suggestion] Ability to add a message to page

### ISSUE THREAD

**Issue by redcatjack** [inferno-collection/Fire-EMS-Pager#4]
Would be nice if there was a way to add a message attached to the page, for example say there is a fire at Postal code 1234 On Alta Street you could something like "/page FIRE Fire reported at 1234 Alta St."
And would show as a notification above the mini-map with the message and type of page

**Comment by cm8263** [comment]
Scott, do you want to have a crack at that idea you had the other day, searching the array for an element like a `,` or a `-` or something, then joining all the elements after that and turning it into a string? Something like:
```
/page <tone> <tone> - Location here
```

I'll talk to you about it in the morning.
***

Thanks for the suggestion redcatjack.

**Comment by cm8263** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add location to page command](https://trello.com/c/FfEyFmNs/1-add-location-to-page-command)

**Comment by ScottUK** [comment]
Should be completed my tomorrow.

**Comment by AngryAlaskan** [comment]
Super excited for that addition. Thanks!

**Comment by redcatjack** [comment]
Any updates? You said "Should be completed by tomorrow." and that was now 3 days ago :(

**Comment by cm8263** [comment]
> Any updates? You said "Should be completed by tomorrow." and that was now 3 days ago :(

Sorry Red, Scott is away for another day and I've just come back for the first time in 3 days, won't be much longer!

**Comment by cm8263** [comment]
Just an update, it's been written and is in the process of being tested by our Alpha Testers; we've decided to add it to the next public release, which will be in a few days :smile:

**Comment by cm8263** [comment]
Added in Public Beta Version 4.4 (https://github.com/inferno-collection/Fire-EMS-Pager/commit/1de02ec4060ef2f3d0dd49d4326cea65e4fb8712).

Thank you so much for waiting!
