### ISSUE TITLE
[Bug] Unequal timings between clients

### ISSUE THREAD

**Issue by cm8263** [inferno-collection/Fire-EMS-Pager#5]
**Describe the bug**
Clients with disabled pagers wait for less amount of time than clients with enabled pagers, when using the /page command, resulting in tones being able to be paged over other tones.

**Steps to reproduce**
Have a client page tones, if that client, or any other client, does not have there pager enabled, they are forced to wait a shorter amount of time before being able to page more tones, than a client who has their pager enabled.

**Expected behavior**
All clients should have to wait the same amount of time, that is, as long as tones are being paged, more should not be able to be paged over the top.

**Screenshots**
N/A

**Resource version**
4.38

**Additional context**
Affects all versions of the resource.

**Comment by cm8263** [comment]
Mission-critical in Public Beta Version 4.5, due to the fact people are more likely to accidentally play tones over each other if they are not tuned to, and therefore cannot hear, a tone that is already playing.

**Comment by RevanHD** [comment]
@cm8263 Do you have discord? Sorry I dont really use github. add me @Skila#5566

**Comment by cm8263** [comment]
> @cm8263 Do you have discord? Sorry I dont really use github. add me @skila#5566

I do, I'm taking a break from it at the moment and will check it next week, but feel free to join it: https://discord.gg/5GZ3Jzt

**Comment by cm8263** [comment]
Fixed for [Public Beta Version 4.5](https://github.com/inferno-collection/Fire-EMS-Pager/milestone/1).
