### ISSUE TITLE
Whitelist command to add to authorized users (with levels)

### ISSUE THREAD

**Issue by ResqDiver1317** [inferno-collection/Fire-EMS-Pager#6]
**Is your feature request related to a problem? Please describe.**
Technically no, but at the same time, sortof. We are in the process of setting up the pager/siren on our server and so far, we are really liking it. We also discovered we are going to need to use the whitelist function but adding EVERYONE in the departments that need access to the pager will be tedious. 

**Describe the solution you would like**
A command that would allow us to add users to the whitelist while in game (and must be whitelisted to add them) would be helpful. 
Basically, something where we would type "/firewhitelist steam:theirhexid true false false false" for someone who should only have access to the pager command or "/firewhitelist steam:theirhexid true true true true" for department command staff who should be able to send/receive pages as well.

**Describe alternatives you have considered**
An alternative is allow in the config where you only need whitelisted to run the page, cancelpage, and firesiren commands, but the pager command can be done by anyone. (I really don't care if an occasional random turns on the pager and gets the pages, as long as they can't send pages. 

**Additional context**

**Comment by cm8263** [comment]
Hello, sorry for the slow response.

This was something we thought about right at the beginning of the project, that we more or less forgot about after adding the JSON whitelist system (sorry lol), but it is definitely something we can revisit.

I will have a play around and decide if it is something we will add to the main version, or just as a wiki tutorial ([like this](https://github.com/inferno-collection/Fire-EMS-Pager/wiki/Calling-the-fire-siren-from-an-external-resource), either way, I will let you know.

Fair warning that I am very busy IRL at the moment, and I cannot give you a timeline for this, but it will happen sooner or later, bear with me!

Thanks for the suggestion.

**Comment by ResqDiver1317** [comment]
If it's a DIY guide to implementing, I'm ok with that. I don't mind doing a little work as long as I have a guide to follow so I know what to do. I appreciate your work on this script!

**Comment by cm8263** [comment]
Took a few more hours than I would like to admit, but it is done. Will be released in [Public Beta Version 4.5](https://github.com/inferno-collection/Fire-EMS-Pager/milestone/1).

Thanks for your patience.
