### ISSUE TITLE
Pager should only make sound/show text for groups actually paged.

### ISSUE THREAD

**Issue by ResqDiver1317** [inferno-collection/Fire-EMS-Pager#7]
**Is your feature request related to a problem? Please describe.**
The pager should only make noise, display text for the group paged. Currently, all groups hear the pager.

**Describe the solution you would like**
Only groups actually paged should hear/see anything. 

If paging only Fire: The pager should play these tones. Vibration, then fire, then display the text and ONLY those set to Fire should hear/see it. Medical, Rescue, and Other should see/hear nothing.
If paging Medical and Fire, the pager should play Vibration, Medical, Fire, then display the text and ONLY Medical and Fire should see it. Rescue and Other should see/hear nothing at all. 
If paging Other, the pager should play Vibration, Other, then display text and ONLY other should see it. Medical, Fire, and Rescue should see/hear nothing.

**Comment by cm8263** [comment]
@ResqDiver1317 How would this work with the `/cancelpage` command?

**Comment by ResqDiver1317** [comment]
The cancel page should also be group specific. IRL, since personnel would already have the active call, their pager would be in "open" mode (picking up all traffic on channel) and the dispatch would just radio any group that needs to disregard/cancel (Motor vehicle accident, FD arrives on scene and determines non injury, dispatch can cancel EMS). Since we can't actually carry voice over your pager script, it would be best if the "cancelpage" command required groups to cancel, just like sending pages. So if we show up on a scene as FD, and not need EMS like my example above, we can just do "/cancelpage medical" or if one of us shows up and it's just a minor scene off the road and no extra units are needed from Fire or EMS, we can do "/cancelpage fire medical"

**Comment by cm8263** [comment]
Sounds good, thanks

**Comment by cm8263** [comment]
A nice easy suggestion to implement, all done. Will be released in [Public Beta Version 4.5](https://github.com/inferno-collection/Fire-EMS-Pager/milestone/1).

Thanks for your patience.
