### ISSUE TITLE
[Suggestion] Allow different stations to have different distances you can hear the siren from, and support for multiple different siren sounds

### ISSUE THREAD

**Issue by redcatjack** [inferno-collection/Fire-EMS-Pager#8]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you would like**
Allow different stations to have different distances you can hear the siren from,
for example the Sandy Fire Station can have a siren radius of "600". 
But the Paleto Fire Siren can have a radius of "800".

Also allowing different stations to have different sounds for the siren.
The config could look something like:
`table.insert(config.stations, {name = "pb", sirenradius = 800, sirensound = "paletobaysiren.mp3", loc = vector3(-379.53, 6118.32, 31.85)}) -- Paleto Bay
`

**Describe alternatives you have considered**
N/A

**Additional context**
Semi-Unrelated. Could also possible make another resource (with mentioned above features), but strip out the pager feature, but leave the siren side in so you can set up sirens unrelated to Fire Stations.

**Comment by cm8263** [comment]
That's two very interesting ideas, thanks. I'm super busy with exams at the moment, but once I get back, I'll definitely take a look a this 👍

**Comment by cm8263** [comment]
In regards to a separate resource just for sirens, I would just delete the lines of code related to the pager, you won't affect the siren side of things.

**Comment by cm8263** [comment]
Wasn't able to add multiple sound files sadly, due to the way the NUI is set-up to function, I was, however, able to add per-siren radiuses, that part will be ready for [Public Beta Version 4.5](https://github.com/inferno-collection/Fire-EMS-Pager/milestone/1).

**Comment by cm8263** [comment]
With the new audio system, multiple audio files should be achievable! https://github.com/inferno-collection/Fire-EMS-Pager/commit/12e7b66619ee09a3a99f145a496fa7a500fdc78a

**Comment by cm8263** [comment]
Added in https://github.com/inferno-collection/Fire-EMS-Pager/commit/679835962522e7146a3a781112c7ccc6d76c1211. Once pushed to master, I'll reclose this suggestion.

**Comment by redcatjack** [comment]
Nice to see this get added!
Thanks :)

**Comment by TomsenJohnsen** [comment]
I was wondering if you could maybe send me the Alarm script or just the Alarm Code :)

**Comment by cm8263** [comment]
> I was wondering if you could maybe send me the Alarm script or just the Alarm Code :)

https://github.com/inferno-collection/Fire-Alarm
