### ISSUE TITLE
[Suggestion] AcePermissions

### ISSUE THREAD

**Issue by RevanHD** [inferno-collection/Fire-EMS-Pager#9]
A new feature like AcePermissions would be really good. Atleast then those of us who prefer discord permissions over steam ID's can easily adapt the Pager script when necessary. Through AcePerms we are able to give our Fire/EMS access through their own corresponding groups that match the discord. Please release a version of this for us! It would be a greatly needed addition!

**Comment by cm8263** [comment]
Will look into the technical aspect of implementation, then we'll see if it will be added to master, or as an optional tutorial on the wiki :+1:

**Comment by cm8263** [comment]
@RevanHD How are you using Discord permissions out of interest, is it just:
```
add_principal identifier.DiscordIDGoesHere <Group>
```

**Comment by cm8263** [comment]
Either way ^, after looking into it, it shouldn't be too difficult to implement into the master.

**Comment by cm8263** [comment]
All set-up and ready for [Public Beta Version 4.5](https://github.com/inferno-collection/Fire-EMS-Pager/milestone/1).
